export const MUTATION_TYPES = {
  INCREMENT_COUNTER: "incrementCounter",
  CHANGE_MSG: "changeMsg",
  POPULATE_SHOPPING_LISTS: "POPULATE_SHOPPING_LISTS",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT"
};
